'use client';

const records: Record<string,{image?:string;alt?:string;caption?:string;scope:string;result:string}> = {
 'SQL Server Ingestion Framework': {scope:'Documented controlled SQL Server pilot. Workplace adaptations, source files, server names, database objects, credentials and operational logs remain private. No new database execution was performed for this portfolio.',result:'The curated pilot record describes separate profiling, read-only preflight, schema planning, explicit provisioning and loading gates. A first pilot load created the expected records; repeating the same source preserved the row count without duplicates. Persistent target metadata and job monitoring supported operator review.'},
 'Healthcare AI Analytics': {image:'/evidence/healthcare-architecture.png',alt:'Healthcare analytics architecture: prepared data, semantic definitions and validation feed governed question answering and reporting.',caption:'Existing architecture overview from the project archive—not a live application screenshot.',scope:'Graduate prototype; not a production clinical, financial or reimbursement decision system. Raw healthcare data is not included.',result:'The documented workflow separates supported questions from unsupported requests. Missing outcome fields lead to an explanation and research plan, not an invented clinical answer.'},
 'NovaStream Model Validation': {image:'/evidence/novastream-model-comparison.png',alt:'Saved comparison chart for Logistic Regression, Decision Tree, Random Forest and Gradient Boosting, covering accuracy, precision, recall and ROC AUC.',caption:'Historical saved evaluation chart. This portfolio update did not rerun training; results are not a claim of production performance.',scope:'Premium-upgrade proof of concept that informed the Healthcare AI Analytics approach. These results are not healthcare or clinical validation. Customer-level workbooks and scoring records remain private.',result:'The saved evaluation compares four classifiers using multiple metrics. Reviewing recall alongside accuracy exposes tradeoffs that a single headline score would hide.'},
 'MIRA — Model-Agnostic AI Workspace': {scope:'Architecture includes a local read-only MCP adapter and human-facing control center. The separate September 6, 2026 execution pilot tested one fixed Python task, not general unattended orchestration.',result:'The source assessment documents explicit approval, a separate Run action, isolated execution, result verification against the approved manifest and receipt, and durable completion. My role: architecture and governance direction with AI-assisted implementation.'},
 'Professional Portfolio Platform': {scope:'Curated project documentation and knowledge organization. Private source archives and employment records are not shared here.',result:'Career claims, reusable professional artifacts and AI handoff notes are organized in version-controlled project context. This portfolio is one consumer of that curated source material.'},
 'Data Management': {scope:'Graduate warehouse design summary. Source datasets and private course material are not distributed.',result:'Python normalization and SQL staging, dimensions and facts form a repeatable analytical data path. This case study describes the design; it does not claim a new benchmark or production deployment.'}
};
export function ProjectEvidence({title,overview,approach,evidence}:{title:string;overview:string;approach:string[];evidence:string[]}){
 const r=records[title];
 const study=`# ${title}\n\n## Overview\n${overview}\n\n## Approach\n${approach.map(x=>'- '+x).join('\n')}\n\n## Documented evidence\n${evidence.map(x=>'- '+x).join('\n')}\n\n## Interpretation\n${r.result}\n\n## Scope and limitations\n${r.scope}\n\nPrepared from curated project records for the personal portfolio. Evidence is historical, not a new execution or certification.\n`;
 return <section className="evidence-detail" aria-label="Project evidence and case study">
 {r.image&&<figure><a href={(process.env.NEXT_PUBLIC_BASE_PATH || '')+r.image} target="_blank" rel="noreferrer" aria-label={`Open full-size evidence for ${title}`}><img src={(process.env.NEXT_PUBLIC_BASE_PATH || '')+r.image} alt={r.alt} loading="lazy"/></a><figcaption>{r.caption} Select the image to open it full size.</figcaption></figure>}
 <h3>What this demonstrates</h3><p>{r.result}</p>
 <details className="case-study"><summary>Read the case study</summary><h4>Problem and purpose</h4><p>{overview}</p><h4>Approach</h4><ol>{approach.map(x=><li key={x}>{x}</li>)}</ol><h4>Scope</h4><p>{r.scope}</p></details>
 <a className="evidence-download" href={'data:text/markdown;charset=utf-8,'+encodeURIComponent(study)} download={title.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-case-study.md'}>Download case study (text) ↓</a>
 <p className="evidence-note">{r.scope}</p>
 </section>;
}
