'use client';

const records: Record<string,{image?:string;alt?:string;caption?:string;scope:string;result:string}> = {
 'AI Governance & Evidence': {scope:'Evidence comes from documented prototypes and recorded local test results. Production-wide validation remains a future step.',result:'This case study brings together governance practices demonstrated across MIRA, Healthcare AI Analytics, and PPP: human approval, checkpoint recovery, validated answers, and traceable links between claims and supporting evidence.'},
 'SQL Server Ingestion Framework': {scope:'Documented controlled SQL Server pilot. Workplace adaptations, source files, source schemas, server names, database objects, credentials and operational logs remain private. No new database execution was performed for this portfolio.',result:'The curated pilot record documents controlled schema onboarding, repeat-load idempotency checks, and operator review practices for reliable loading workflows.'},
 'Healthcare AI Analytics': {image:'/evidence/healthcare-architecture.png',alt:'Healthcare analytics architecture: prepared data, semantic definitions and validation feed governed question answering and reporting.',caption:'Existing architecture overview from the project archive—not a live application screenshot.',scope:'Graduate prototype; not a production clinical, financial or reimbursement decision system. Raw healthcare data is not included.',result:'The documented workflow separates supported questions from unsupported requests. Missing outcome fields lead to an explanation and research plan, not an invented clinical answer.'},
 'NovaStream Model Validation': {image:'/evidence/novastream-model-comparison.png',alt:'Saved comparison chart for Logistic Regression, Decision Tree, Random Forest and Gradient Boosting, covering accuracy, precision, recall and ROC AUC.',caption:'Historical saved evaluation chart. This portfolio update did not rerun training; results are not a claim of production performance.',scope:'Premium-upgrade proof of concept that informed the Healthcare AI Analytics approach. These results are not healthcare or clinical validation. Customer-level workbooks and scoring records remain private.',result:'The saved evaluation compares four classifiers using multiple metrics. Reviewing recall alongside accuracy exposes tradeoffs that a single headline score would hide.'},
 'MIRA — Model-Agnostic AI Workspace': {scope:'Local prototype evidence, not a production deployment. The recovery report records one automated test passing; it does not establish live switching between external LLMs or automatic coordination between separate chat applications. The earlier September 6, 2026 Hello World pilot remains a separate fixed-task milestone. This portfolio update did not rerun either test.',result:'The saved recovery-test report records checkpoint resume, an enforced human-approval gate, continuation of helper/actor context, duplicate-free semantic rows on event replay, and a traceable handoff result. My role: architecture and governance direction with AI-assisted implementation.'},
 'Professional Portfolio Platform': {scope:'Curated project documentation and knowledge organization. Private source archives and employment records are not shared here.',result:'Career claims, reusable professional artifacts and AI handoff notes are organized in version-controlled project context. This portfolio is one consumer of that curated source material.'},
 'Data Management': {scope:'Graduate warehouse design summary. Source datasets and private course material are not distributed.',result:'Python normalization and SQL staging, dimensions and facts form a repeatable analytical data path. This case study describes the design; it does not claim a new benchmark or production deployment.'}
};
export function ProjectEvidence({title,overview,approach,evidence}:{title:string;overview:string;approach:string[];evidence:string[]}){
 const r=records[title];
 const supportingReports: Record<string,string> = {'SQL Server Ingestion Framework':'sql-server-ingestion-evidence.md','Healthcare AI Analytics':'healthcare-analytics-evidence.md','NovaStream Model Validation':'novastream-validation-evidence.md','Professional Portfolio Platform':'ppp-evidence.md','Data Management':'data-management-evidence.md'};
 const report=title==='AI Governance & Evidence'?'ai-governance-evidence.pdf':supportingReports[title]?.replace('.md','.pdf');
 const isMira=title==='MIRA — Model-Agnostic AI Workspace';
 const proofPath=(process.env.NEXT_PUBLIC_BASE_PATH || '')+'/evidence/mira-ingestion-recovery-checkpoint-proof.pdf';
 const study=`# ${title}\n\n## Overview\n${overview}\n\n## Approach\n${approach.map(x=>'- '+x).join('\n')}\n\n## Documented evidence\n${evidence.map(x=>'- '+x).join('\n')}\n\n## Interpretation\n${r.result}\n\n## Scope and limitations\n${r.scope}\n\nPrepared from curated project records for the personal portfolio. Evidence is historical, not a new execution or certification.\n`;
 return <section className="evidence-detail" aria-label="Project evidence and case study">
 {r.image&&<figure><a href={(process.env.NEXT_PUBLIC_BASE_PATH || '')+r.image} target="_blank" rel="noreferrer" aria-label={`Open full-size evidence for ${title}`}><img src={(process.env.NEXT_PUBLIC_BASE_PATH || '')+r.image} alt={r.alt} loading="lazy"/></a><figcaption>{r.caption} Select the image to open it full size.</figcaption></figure>}
 <h3>What this demonstrates</h3><p>{r.result}</p>
 {report&&<section aria-label="Supporting evidence report"><h3>Supporting evidence</h3><p>{title==='Data Management'?'Design documentation; final load outcomes still need validation.':'Source-based documentation of the work, recorded outcomes, and limits. Historical results were not rerun for this update.'}</p><a className="evidence-download" href={(process.env.NEXT_PUBLIC_BASE_PATH || '')+'/evidence/'+report} download>Download evidence report (PDF) ↓</a></section>}
 {isMira&&<section aria-label="MIRA recovery test evidence">
 <h3>Checkpoint recovery and handoff</h3>
 <h4>What we tested</h4><p>Whether an interrupted ingestion workflow could resume from saved checkpoint context, require human approval, and replay events without adding duplicate semantic rows.</p>
 <h4>How it was tested</h4><p>A targeted automated test exercised checkpointed helper/actor continuation and recorded the handoff outcome. This tests the recovery mechanism; it is not a demonstration of a live external model switch.</p>
 <h4>Recorded outcome</h4><p>The saved test report records one test passed, with three other tests deselected. It reports checkpoint recovery, approval enforcement, replay safety, and a traceable result.</p>
 <h4>Supporting documentation</h4><p><a className="evidence-download" href={proofPath} download>Download recovery test report (PDF) ↓</a></p>
 <p>The earlier Hello World pilot demonstrated human-approved fixed-task execution and verification. This recovery test adds a distinct continuity and handoff check.</p>
 </section>}
 <details className="case-study"><summary>Read the case study</summary><h4>Problem and purpose</h4><p>{overview}</p><h4>Approach</h4><ol>{approach.map(x=><li key={x}>{x}</li>)}</ol><h4>Scope</h4><p>{r.scope}</p></details>
 <a className="evidence-download" href={(process.env.NEXT_PUBLIC_BASE_PATH || '')+'/evidence/'+title.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-case-study.pdf'} download>Download case study (PDF) ↓</a>
 <p className="evidence-note">{r.scope}</p>
 </section>;
}
